xcodeproj 'Mantle-HAL.Tests'
workspace '../Mantle-HAL'
inhibit_all_warnings!

def import_pods
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta', '~> 0.2.4'
  pod 'Mantle-HAL-Remix', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
